name: CD

on:
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always
  CI: false

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            target: "aarch64-apple-darwin"
          - platform: "macos-13"
            target: "x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            target: "x86_64-unknown-linux-gnu"
          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: build static server
        run: cd src-static-server && cargo build --release

      - name: copy static server binary (non windows)
        if: matrix.platform != 'windows-latest'
        run: cp src-static-server/target/release/static-server src-tauri/bin/static-server-${{ matrix.target }}

      - name: copy static server binary (windows only)
        if: matrix.platform == 'windows-latest'
        run: cp src-static-server/target/release/static-server.exe src-tauri/bin/static-server-${{ matrix.target }}.exe

      - name: install frontend dependencies
        run: yarn install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "Legends of Dynasties v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
